/**
 * District YouTube channel list.
 *
 * To add or update a district, just edit this file and redeploy.
 * The `id` must match the districtId used in DynamoDB and the frontend.
 */



export const DISTRICTS = [
  { id: 'show-low-unified', name: 'Show Low Unified', youtubeUrl: 'http://youtube.com/@ShowLowTV/streams' },
  { id: 'ajo-unified', name: 'Ajo Unified', youtubeUrl: 'https://www.youtube.com/@ajounifiedschooldistrict3161/streams' },
  { id: 'apache-junction-unified', name: 'Apache Junction Unified', youtubeUrl: 'https://www.youtube.com/@ajusd43/streams' },
  { id: 'alhambra-elementary', name: 'Alhambra Elementary', youtubeUrl: 'https://www.youtube.com/@alhambraESD/streams' },
  { id: 'indian-oasis-baboquivari', name: 'Indian Oasis-Baboquivari', youtubeUrl: 'https://www.youtube.com/@BaboquivariEducation/streams' },
  { id: 'bullhead-city', name: 'Bullhead City Elementary', youtubeUrl: 'https://www.youtube.com/@BCSDBoard/streams' },
  { id: 'blue-ridge-unified', name: 'Blue Ridge Unified', youtubeUrl: 'https://www.youtube.com/@blueridgeunifiedschooldist9674/streams' },
  { id: 'cartwright-elementary', name: 'Cartwright Elementary', youtubeUrl: 'https://www.youtube.com/@cartwrightschooldistrict8328/streams' },
  { id: 'continental-elementary', name: 'Continental Elementary', youtubeUrl: 'https://www.youtube.com/@cesd39/streams' },
  { id: 'catalina-foothills-unified', name: 'Catalina Foothills Unified', youtubeUrl: 'https://www.youtube.com/@cfsdlivestream1800/streams' },
  { id: 'casa-grande-union-high', name: 'Casa Grande Union High', youtubeUrl: 'https://www.youtube.com/@cguhsdcasagrandeunionhighs6531/streams' },
  { id: 'cottonwood-oak-creek', name: 'Cottonwood-Oak Creek', youtubeUrl: 'https://www.youtube.com/@COCSDSchoolBoardLiveStream-AZ' },
  { id: 'creighton-elementary', name: 'Creighton Elementary', youtubeUrl: 'https://www.youtube.com/@creightonschooldistrict1138/streams' },
  { id: 'colorado-river-union-high', name: 'Colorado River Union High', youtubeUrl: 'https://www.youtube.com/@CRUHSD/streams' },
  { id: 'chino-valley-unified', name: 'Chino Valley Unified', youtubeUrl: 'https://www.youtube.com/@CVSchoolsAZ/streams' },
  { id: 'douglas-unified', name: 'Douglas Unified', youtubeUrl: 'https://www.youtube.com/@douglasschools9656/streams' },
  { id: 'deer-valley-unified', name: 'Deer Valley Unified', youtubeUrl: 'https://www.youtube.com/@dvusdboard/streams' },
  { id: 'dysart-unified', name: 'Dysart Unified', youtubeUrl: 'https://www.youtube.com/@DysartUSD/streams' },
  { id: 'fountain-hills-unified', name: 'Fountain Hills Unified', youtubeUrl: 'https://www.youtube.com/@fhusdyoutube130/streams' },
  { id: 'florence-unified', name: 'Florence Unified', youtubeUrl: 'https://www.youtube.com/@FUSDVideoandLiveStreamChannel/streams' },
  { id: 'gadsden-elementary', name: 'Gadsden Elementary', youtubeUrl: 'https://www.youtube.com/@GESD32/streams' },
  { id: 'gilbert-unified', name: 'Gilbert Unified', youtubeUrl: 'https://www.youtube.com/@gilbertpublicschools6525/streams' },
  { id: 'glendale-elementary', name: 'Glendale Elementary', youtubeUrl: 'https://www.youtube.com/@glendaleelementary/streams' },
  { id: 'higley-unified', name: 'Higley Unified', youtubeUrl: 'https://www.youtube.com/@HigleyUnifiedSchoolDistrict60/streams' },
  { id: 'humboldt-unified', name: 'Humboldt Unified', youtubeUrl: 'https://www.youtube.com/@HUSD22/streams' },
  { id: 'isaac-school', name: 'Isaac School District', youtubeUrl: 'https://www.youtube.com/playlist?list=PLleRSbzWjUSl2BDBB-Hsxj4Q7Wc8sXt_P' },
  { id: 'jo-combs-unified', name: 'J.O. Combs Unified', youtubeUrl: 'https://www.youtube.com/@JOCombsUnifiedSchoolDistrict/streams' },
  { id: 'kyrene-elementary', name: 'Kyrene Elementary', youtubeUrl: 'https://www.youtube.com/@KyreneSchoolDistrict/streams' },
  { id: 'litchfield-elementary', name: 'Litchfield Elementary', youtubeUrl: 'https://www.youtube.com/@LESD79/streams' },
  { id: 'littleton-elementary', name: 'Littleton Elementary', youtubeUrl: 'https://www.youtube.com/@lesdvideo/streams' },
  { id: 'lake-havasu-unified', name: 'Lake Havasu Unified', youtubeUrl: 'https://www.youtube.com/@lhusdlakehavasuschools3555/videos' },
  { id: 'liberty-elementary', name: 'Liberty Elementary', youtubeUrl: 'https://www.youtube.com/@libertydistrictcloud3260/streams' },
  { id: 'madison-elementary', name: 'Madison Elementary', youtubeUrl: 'https://www.youtube.com/@madisonyoutube9137/streams' },
  { id: 'maricopa-unified', name: 'Maricopa Unified', youtubeUrl: 'https://www.youtube.com/@MaricopaUnified/streams' },
  { id: 'mesa-unified', name: 'Mesa Unified', youtubeUrl: 'https://www.youtube.com/@mpsazTV/streams' },
  { id: 'osborn-elementary', name: 'Osborn Elementary', youtubeUrl: 'https://www.youtube.com/@osbornschools/streams' },
  { id: 'page-unified', name: 'Page Unified', youtubeUrl: 'https://www.youtube.com/@pageunifiedschooldistrict8105/streams' },
  { id: 'phoenix-elementary', name: 'Phoenix Elementary', youtubeUrl: 'https://www.youtube.com/@phxschools/streams' },
  { id: 'prescott-unified', name: 'Prescott Unified', youtubeUrl: 'https://www.youtube.com/@prescottunifiedschooldistr4802/streams' },
  { id: 'peoria-unified', name: 'Peoria Unified', youtubeUrl: 'https://www.youtube.com/@PUSDOfficialChannel/streams' },
  { id: 'pinon-unified', name: 'Pinon Unified', youtubeUrl: 'https://www.youtube.com/@pusdsuperintendent1146/streams' },
  { id: 'paradise-valley-unified', name: 'Paradise Valley Unified', youtubeUrl: 'https://www.youtube.com/@PVSchools/streams' },
  { id: 'queen-creek-unified', name: 'Queen Creek Unified', youtubeUrl: 'https://www.youtube.com/@QCUSD95/streams' },
  { id: 'round-valley-unified', name: 'Round Valley Unified', youtubeUrl: 'https://www.youtube.com/@rvusdelks5398/streams' },
  { id: 'sahuarita-unified', name: 'Sahuarita Unified', youtubeUrl: 'https://www.youtube.com/@sahuaritausd30' },
  { id: 'laveen-elementary', name: 'Laveen Elementary', youtubeUrl: 'https://www.youtube.com/@schoolboard8506/streams' },
  { id: 'scottsdale-unified', name: 'Scottsdale Unified', youtubeUrl: 'https://www.youtube.com/@ScottsdaleUSD/streams' },
  { id: 'santa-cruz-valley-union-high', name: 'Santa Cruz Valley Union High', youtubeUrl: 'https://www.youtube.com/@SCVCommunications' },
  { id: 'santa-cruz-valley-unified', name: 'Santa Cruz Valley Unified', youtubeUrl: 'https://www.youtube.com/@SCVCommunications/videos' },
  { id: 'saddle-mountain-unified', name: 'Saddle Mountain Unified', youtubeUrl: 'https://www.youtube.com/@smusd90/streams' },
  { id: 'somerton-elementary', name: 'Somerton Elementary', youtubeUrl: 'https://www.youtube.com/@somertonschooldistrict6894/streams' },
  { id: 'sierra-vista-unified', name: 'Sierra Vista Unified', youtubeUrl: 'https://www.youtube.com/@svusdadmin9065/streams' },
  { id: 'tempe-union-high', name: 'Tempe Union High', youtubeUrl: 'https://www.youtube.com/@TempeUnionHighSchoolDistrict/streams' },
  { id: 'toltec-elementary', name: 'Toltec Elementary', youtubeUrl: 'https://www.youtube.com/@toltecschooldistrict1054/streams' },
  { id: 'tolleson-union-high', name: 'Tolleson Union High', youtubeUrl: 'https://www.youtube.com/@TUHSD214/streams' },
  { id: 'tucson-unified', name: 'Tucson Unified', youtubeUrl: 'https://www.youtube.com/@TUSDMedia/streams' },
  { id: 'washington-elementary', name: 'Washington Elementary', youtubeUrl: 'https://www.youtube.com/@WESDMediaServices/streams' },
  { id: 'winslow-unified', name: 'Winslow Unified', youtubeUrl: 'https://www.youtube.com/@winslowschools861/streams' },
  { id: 'wickenburg-unified', name: 'Wickenburg Unified', youtubeUrl: 'https://www.youtube.com/@wusd9433/streams' },
  { id: 'yuma-elementary', name: 'Yuma Elementary', youtubeUrl: 'https://www.youtube.com/@YumaSchoolDistrictOne/streams' },
  { id: 'marana-unified', name: 'Marana Unified', youtubeUrl: 'https://www.youtube.com/c/MaranaUnifiedSchoolDistrict06/streams' },
  { id: 'roosevelt-elementary', name: 'Roosevelt Elementary', youtubeUrl: 'https://www.youtube.com/playlist?list=PLzdruG2V2pvdQyW4USv95dvgHsc8VwT4H' },
  { id: 'tempe-school', name: 'Tempe Elementary', youtubeUrl: 'https://www.youtube.com/channel/UCaqWbV8gwjeZU8ZUK0K-23A/videos' },
  { id: 'agua-fria-union-high', name: 'Agua Fria Union High', youtubeUrl: 'https://www.youtube.com/@AFUHSD/streams' },
  { id: 'vail-unified', name: 'Vail Unified', youtubeUrl: 'https://www.youtube.com/@vailstreaming387' },
  { id: 'joseph-city-unified', name: 'Joseph City Unified', youtubeUrl: 'https://www.youtube.com/@josephcityschoolsboardmeet9497/streams' },
  { id: 'chandler-unified', name: 'Chandler Unified', youtubeUrl: 'https://www.youtube.com/@chandlerusdgoverningboard9774/streams' },
  { id: 'kingman-unified', name: 'Kingman Unified', youtubeUrl: 'https://www.youtube.com/@KUSD20/streams' },
  { id: 'yuma-union-high', name: 'Yuma Union High', youtubeUrl: 'https://www.youtube.com/playlist?list=PL4XNU-h8243KAGIBVNykbZ1n4oiC1VLwD' },
  { id: 'casa-grande-elementary', name: 'Casa Grande Elementary', youtubeUrl: 'https://www.youtube.com/playlist?list=PLn_Oj0Kf7oPpAgI4tkeGhNeQK1jA8104x' },
  { id: 'cave-creek-unified', name: 'Cave Creek Unified', youtubeUrl: 'https://www.youtube.com/playlist?list=PLwRolyepcxIpPmB3dK6pckR7SvdhSkwAY' },
  { id: 'phoenix-union-high', name: 'Phoenix Union High', youtubeUrl: 'https://www.youtube.com/playlist?list=PLehNBah3JnNrjNa6c4EogrMskrOY5n_2z' },
];
