export interface DistrictMeta {
  id: string;
  name: string;
  meetings: number;
  faqs: string[];
}

export const DISTRICTS: DistrictMeta[] = [
  {
    id: "agua-fria-union-high",
    name: "Agua Fria Union High",
    meetings: 3,
    faqs: [
      "What safety upgrades were approved at Agua Fria schools?",
      "Were there any teacher hiring updates at the last board meeting?",
      "What budget transfers did the Agua Fria board approve?",
    ],
  },
  {
    id: "ajo-unified",
    name: "Ajo Unified",
    meetings: 3,
    faqs: [
      "What curriculum changes were discussed at Ajo Unified?",
      "Were there any facility renovation updates at Ajo Unified?",
      "What personnel decisions were made at the last Ajo Unified meeting?",
    ],
  },
  {
    id: "alhambra-elementary",
    name: "Alhambra Elementary",
    meetings: 3,
    faqs: [
      "What reading programs were discussed at Alhambra Elementary?",
      "Were there any budget approvals at the last Alhambra board meeting?",
      "What staff changes were reported at Alhambra Elementary?",
    ],
  },
  {
    id: "apache-junction-unified",
    name: "Apache Junction Unified",
    meetings: 3,
    faqs: [
      "What construction or facility projects were approved at Apache Junction Unified?",
      "Were there budget discussions at the last Apache Junction board meeting?",
      "What curriculum or instructional updates were discussed?",
    ],
  },
  {
    id: "blue-ridge-unified",
    name: "Blue Ridge Unified",
    meetings: 3,
    faqs: [
      "What extracurricular or athletics decisions were made at Blue Ridge Unified?",
      "Were there any teacher contract discussions at Blue Ridge?",
      "What technology initiatives were approved at Blue Ridge Unified?",
    ],
  },
  {
    id: "bullhead-city",
    name: "Bullhead City Elementary",
    meetings: 3,
    faqs: [
      "What school safety measures were discussed at Bullhead City?",
      "Were there any enrollment or boundary changes discussed?",
      "What budget updates were reported at Bullhead City Elementary?",
    ],
  },
  {
    id: "cartwright-elementary",
    name: "Cartwright Elementary",
    meetings: 3,
    faqs: [
      "What special education programs were discussed at Cartwright Elementary?",
      "Were there facility improvement approvals at the last Cartwright meeting?",
      "What personnel changes were announced at Cartwright Elementary?",
    ],
  },
  {
    id: "casa-grande-elementary",
    name: "Casa Grande Elementary",
    meetings: 3,
    faqs: [
      "What after-school programs were discussed at Casa Grande Elementary?",
      "Were there budget transfers approved at the last Casa Grande meeting?",
      "What curriculum updates were made at Casa Grande Elementary?",
    ],
  },
  {
    id: "casa-grande-union-high",
    name: "Casa Grande Union High",
    meetings: 3,
    faqs: [
      "What career and technical education programs were discussed?",
      "Were there athletics or activity fee changes at Casa Grande Union High?",
      "What building projects were approved at Casa Grande Union High?",
    ],
  },
  {
    id: "catalina-foothills-unified",
    name: "Catalina Foothills Unified",
    meetings: 3,
    faqs: [
      "What academic achievement updates were reported at Catalina Foothills?",
      "Were there any policy changes approved at the last board meeting?",
      "What community partnerships were discussed at Catalina Foothills Unified?",
    ],
  },
  {
    id: "cave-creek-unified",
    name: "Cave Creek Unified",
    meetings: 3,
    faqs: [
      "What school construction projects were discussed at Cave Creek Unified?",
      "Were there any controversial curriculum items at Cave Creek board meetings?",
      "What budget reports were presented at the last Cave Creek meeting?",
    ],
  },
  {
    id: "chandler-unified",
    name: "Chandler Unified",
    meetings: 3,
    faqs: [
      "What new schools or boundary changes were discussed at Chandler Unified?",
      "Were there any teacher pay or contract decisions made?",
      "What technology programs were approved at Chandler Unified?",
    ],
  },
  {
    id: "chino-valley-unified",
    name: "Chino Valley Unified",
    meetings: 3,
    faqs: [
      "What rural education challenges were discussed at Chino Valley Unified?",
      "Were there any transportation updates at the last board meeting?",
      "What budget items were approved at Chino Valley Unified?",
    ],
  },
  {
    id: "colorado-river-union-high",
    name: "Colorado River Union High",
    meetings: 3,
    faqs: [
      "What career readiness programs were discussed at Colorado River Union High?",
      "Were there facility or renovation approvals at the last board meeting?",
      "What graduation requirement changes were discussed?",
    ],
  },
  {
    id: "continental-elementary",
    name: "Continental Elementary",
    meetings: 3,
    faqs: [
      "What literacy programs were discussed at Continental Elementary?",
      "Were there any staffing updates at the last Continental board meeting?",
      "What community engagement initiatives were mentioned?",
    ],
  },
  {
    id: "cottonwood-oak-creek",
    name: "Cottonwood-Oak Creek",
    meetings: 3,
    faqs: [
      "What school improvement plans were discussed at Cottonwood-Oak Creek?",
      "Were there any budget shortfalls or surpluses reported?",
      "What special education updates were made at Cottonwood-Oak Creek?",
    ],
  },
  {
    id: "creighton-elementary",
    name: "Creighton Elementary",
    meetings: 3,
    faqs: [
      "What bilingual or ELL programs were discussed at Creighton Elementary?",
      "Were there facility repairs approved at the last board meeting?",
      "What instructional staff changes were announced at Creighton?",
    ],
  },
  {
    id: "deer-valley-unified",
    name: "Deer Valley Unified",
    meetings: 3,
    faqs: [
      "What were the main topics at the last Deer Valley Unified board meeting?",
      "Were there budget discussions at the last Deer Valley meeting?",
      "What new programs were approved at Deer Valley Unified?",
    ],
  },
  {
    id: "douglas-unified",
    name: "Douglas Unified",
    meetings: 3,
    faqs: [
      "What border community education programs were discussed at Douglas Unified?",
      "Were there any grant or funding updates at Douglas Unified?",
      "What facilities decisions were made at the last Douglas board meeting?",
    ],
  },
  {
    id: "dysart-unified",
    name: "Dysart Unified",
    meetings: 3,
    faqs: [
      "What new school construction was discussed at Dysart Unified?",
      "Were there any curriculum or textbook adoption updates?",
      "What budget approvals were made at the last Dysart board meeting?",
    ],
  },
  {
    id: "florence-unified",
    name: "Florence Unified",
    meetings: 3,
    faqs: [
      "What security improvements were discussed at Florence Unified?",
      "Were there any personnel or administrative changes announced?",
      "What academic programs were approved at Florence Unified?",
    ],
  },
  {
    id: "fountain-hills-unified",
    name: "Fountain Hills Unified",
    meetings: 3,
    faqs: [
      "What community feedback was presented at Fountain Hills Unified?",
      "Were there budget discussions at the last Fountain Hills board meeting?",
      "What extracurricular program decisions were made at Fountain Hills?",
    ],
  },
  {
    id: "gadsden-elementary",
    name: "Gadsden Elementary",
    meetings: 3,
    faqs: [
      "What bilingual education updates were reported at Gadsden Elementary?",
      "Were there any federal grant discussions at the last Gadsden meeting?",
      "What facility upgrades were approved at Gadsden Elementary?",
    ],
  },
  {
    id: "gilbert-unified",
    name: "Gilbert Unified",
    meetings: 3,
    faqs: [
      "What were the main topics at the last Gilbert Unified board meeting?",
      "Were there any controversial policy items discussed at Gilbert Unified?",
      "What budget or finance reports were presented at Gilbert Unified?",
    ],
  },
  {
    id: "glendale-elementary",
    name: "Glendale Elementary",
    meetings: 3,
    faqs: [
      "What school improvement initiatives were discussed at Glendale Elementary?",
      "Were there any boundary or enrollment changes at Glendale?",
      "What staff hiring approvals were made at the last Glendale meeting?",
    ],
  },
  {
    id: "higley-unified",
    name: "Higley Unified",
    meetings: 3,
    faqs: [
      "What new school projects were discussed at Higley Unified?",
      "Were there any bond or budget votes at the last Higley board meeting?",
      "What curriculum decisions were made at Higley Unified?",
    ],
  },
  {
    id: "humboldt-unified",
    name: "Humboldt Unified",
    meetings: 3,
    faqs: [
      "What rural school challenges were discussed at Humboldt Unified?",
      "Were there transportation or busing updates at the last meeting?",
      "What personnel decisions were made at Humboldt Unified?",
    ],
  },
  {
    id: "indian-oasis-baboquivari",
    name: "Indian Oasis-Baboquivari",
    meetings: 3,
    faqs: [
      "What tribal education programs were discussed at Indian Oasis-Baboquivari?",
      "Were there any funding or grant updates at the last board meeting?",
      "What language preservation programs were mentioned?",
    ],
  },
  {
    id: "isaac-school",
    name: "Isaac School District",
    meetings: 3,
    faqs: [
      "What school safety updates were reported at Isaac School District?",
      "Were there any budget or finance discussions at the last meeting?",
      "What after-school or enrichment programs were approved at Isaac?",
    ],
  },
  {
    id: "jo-combs-unified",
    name: "J.O. Combs Unified",
    meetings: 3,
    faqs: [
      "What growth or enrollment discussions occurred at J.O. Combs Unified?",
      "Were there facility expansion updates at the last board meeting?",
      "What academic achievement data was presented at J.O. Combs?",
    ],
  },
  {
    id: "joseph-city-unified",
    name: "Joseph City Unified",
    meetings: 3,
    faqs: [
      "What small district challenges were discussed at Joseph City Unified?",
      "Were there any teacher recruitment updates at the last meeting?",
      "What budget approvals were made at Joseph City Unified?",
    ],
  },
  {
    id: "kingman-unified",
    name: "Kingman Unified",
    meetings: 3,
    faqs: [
      "What school construction or renovation projects were approved at Kingman Unified?",
      "Were there any policy debates at the last Kingman board meeting?",
      "What curriculum or instructional updates were discussed at Kingman?",
    ],
  },
  {
    id: "kyrene-elementary",
    name: "Kyrene Elementary",
    meetings: 3,
    faqs: [
      "What technology or STEM programs were discussed at Kyrene Elementary?",
      "Were there any boundary or school assignment changes discussed?",
      "What budget approvals were made at the last Kyrene meeting?",
    ],
  },
  {
    id: "lake-havasu-unified",
    name: "Lake Havasu Unified",
    meetings: 3,
    faqs: [
      "What facility improvement projects were discussed at Lake Havasu Unified?",
      "Were there career and technical education updates at the last meeting?",
      "What personnel changes were approved at Lake Havasu Unified?",
    ],
  },
  {
    id: "laveen-elementary",
    name: "Laveen Elementary",
    meetings: 3,
    faqs: [
      "What new school or growth-related items were discussed at Laveen Elementary?",
      "Were there budget discussions at the last Laveen board meeting?",
      "What instructional program updates were reported at Laveen?",
    ],
  },
  {
    id: "liberty-elementary",
    name: "Liberty Elementary",
    meetings: 3,
    faqs: [
      "What school improvement plans were discussed at Liberty Elementary?",
      "Were there any facility safety updates at the last Liberty meeting?",
      "What staff changes were approved at Liberty Elementary?",
    ],
  },
  {
    id: "litchfield-elementary",
    name: "Litchfield Elementary",
    meetings: 3,
    faqs: [
      "What academic programs were discussed at Litchfield Elementary?",
      "Were there budget or spending approvals at the last Litchfield meeting?",
      "What community events or partnerships were mentioned?",
    ],
  },
  {
    id: "littleton-elementary",
    name: "Littleton Elementary",
    meetings: 3,
    faqs: [
      "What literacy or reading initiatives were discussed at Littleton Elementary?",
      "Were there any school boundary changes discussed?",
      "What staffing approvals were made at the last Littleton board meeting?",
    ],
  },
  {
    id: "madison-elementary",
    name: "Madison Elementary",
    meetings: 3,
    faqs: [
      "What enrichment programs were discussed at Madison Elementary?",
      "Were there any budget or fund transfers approved at the last meeting?",
      "What facilities updates were reported at Madison Elementary?",
    ],
  },
  {
    id: "marana-unified",
    name: "Marana Unified",
    meetings: 3,
    faqs: [
      "What growth or new construction was discussed at Marana Unified?",
      "Were there any teacher pay or benefits discussions at the last meeting?",
      "What curriculum adoption decisions were made at Marana Unified?",
    ],
  },
  {
    id: "maricopa-unified",
    name: "Maricopa Unified",
    meetings: 3,
    faqs: [
      "What new school or expansion plans were discussed at Maricopa Unified?",
      "Were there budget discussions or approvals at the last Maricopa meeting?",
      "What academic achievement reports were presented at Maricopa Unified?",
    ],
  },
  {
    id: "mesa-unified",
    name: "Mesa Unified",
    meetings: 3,
    faqs: [
      "What were the main topics at the last Mesa Unified board meeting?",
      "Were there any budget or finance discussions at Mesa Unified?",
      "What new staff were hired at Mesa Unified?",
    ],
  },
  {
    id: "osborn-elementary",
    name: "Osborn Elementary",
    meetings: 3,
    faqs: [
      "What school safety measures were discussed at Osborn Elementary?",
      "Were there any budget approvals at the last Osborn board meeting?",
      "What instructional or curriculum updates were discussed at Osborn?",
    ],
  },
  {
    id: "page-unified",
    name: "Page Unified",
    meetings: 3,
    faqs: [
      "What Navajo Nation education programs were discussed at Page Unified?",
      "Were there any federal grant or funding updates at the last meeting?",
      "What facility improvements were approved at Page Unified?",
    ],
  },
  {
    id: "paradise-valley-unified",
    name: "Paradise Valley Unified",
    meetings: 3,
    faqs: [
      "What academic programs were discussed at Paradise Valley Unified?",
      "Were there any boundary or school assignment changes discussed?",
      "What budget or spending decisions were made at Paradise Valley Unified?",
    ],
  },
  {
    id: "peoria-unified",
    name: "Peoria Unified",
    meetings: 3,
    faqs: [
      "What were the main topics at the last Peoria Unified board meeting?",
      "Were there budget discussions at Peoria Unified?",
      "What curriculum or instructional updates were approved at Peoria Unified?",
    ],
  },
  {
    id: "phoenix-elementary",
    name: "Phoenix Elementary",
    meetings: 3,
    faqs: [
      "What school improvement updates were discussed at Phoenix Elementary?",
      "Were there any teacher or staff hiring approvals at the last meeting?",
      "What community programs were discussed at Phoenix Elementary?",
    ],
  },
  {
    id: "phoenix-union-high",
    name: "Phoenix Union High",
    meetings: 3,
    faqs: [
      "What career and technical education updates were discussed at Phoenix Union High?",
      "Were there any graduation rate or student achievement reports?",
      "What budget approvals were made at the last Phoenix Union board meeting?",
    ],
  },
  {
    id: "pinon-unified",
    name: "Pinon Unified",
    meetings: 3,
    faqs: [
      "What Navajo education or language programs were discussed at Pinon Unified?",
      "Were there any federal funding updates at the last Pinon board meeting?",
      "What staffing or personnel changes were announced at Pinon Unified?",
    ],
  },
  {
    id: "prescott-unified",
    name: "Prescott Unified",
    meetings: 3,
    faqs: [
      "What school facility projects were discussed at Prescott Unified?",
      "Were there any curriculum debates at the last Prescott board meeting?",
      "What budget approvals were made at Prescott Unified?",
    ],
  },
  {
    id: "queen-creek-unified",
    name: "Queen Creek Unified",
    meetings: 3,
    faqs: [
      "What growth-related construction was discussed at Queen Creek Unified?",
      "Were there bond or budget votes at the last Queen Creek meeting?",
      "What new academic programs were approved at Queen Creek Unified?",
    ],
  },
  {
    id: "roosevelt-elementary",
    name: "Roosevelt Elementary",
    meetings: 3,
    faqs: [
      "What special education program updates were reported at Roosevelt Elementary?",
      "Were there budget or grant discussions at the last Roosevelt meeting?",
      "What community partnerships were mentioned at Roosevelt Elementary?",
    ],
  },
  {
    id: "round-valley-unified",
    name: "Round Valley Unified",
    meetings: 3,
    faqs: [
      "What rural school funding challenges were discussed at Round Valley Unified?",
      "Were there any teacher recruitment updates at the last meeting?",
      "What athletic or extracurricular decisions were made at Round Valley?",
    ],
  },
  {
    id: "saddle-mountain-unified",
    name: "Saddle Mountain Unified",
    meetings: 3,
    faqs: [
      "What school growth plans were discussed at Saddle Mountain Unified?",
      "Were there any facility approvals at the last Saddle Mountain meeting?",
      "What budget items were approved at Saddle Mountain Unified?",
    ],
  },
  {
    id: "sahuarita-unified",
    name: "Sahuarita Unified",
    meetings: 3,
    faqs: [
      "What academic achievement reports were presented at Sahuarita Unified?",
      "Were there any new program approvals at the last Sahuarita meeting?",
      "What budget discussions occurred at Sahuarita Unified?",
    ],
  },
  {
    id: "santa-cruz-valley-unified",
    name: "Santa Cruz Valley Unified",
    meetings: 3,
    faqs: [
      "What bilingual education updates were discussed at Santa Cruz Valley Unified?",
      "Were there any facility projects approved at the last board meeting?",
      "What personnel decisions were made at Santa Cruz Valley Unified?",
    ],
  },
  {
    id: "santa-cruz-valley-union-high",
    name: "Santa Cruz Valley Union High",
    meetings: 3,
    faqs: [
      "What career readiness programs were discussed at Santa Cruz Valley Union High?",
      "Were there any graduation or dropout prevention updates?",
      "What budget approvals were made at the last Santa Cruz Valley Union High meeting?",
    ],
  },
  {
    id: "scottsdale-unified",
    name: "Scottsdale Unified",
    meetings: 3,
    faqs: [
      "What facilities renovation updates were discussed at Scottsdale Unified?",
      "Were there any budget or finance discussions at the last Scottsdale meeting?",
      "What new staff or programs were approved at Scottsdale Unified?",
    ],
  },
  {
    id: "show-low-unified",
    name: "Show Low Unified",
    meetings: 3,
    faqs: [
      "What school facility improvements were discussed at Show Low Unified?",
      "Were there any athletic program updates at the last Show Low meeting?",
      "What budget items were approved at Show Low Unified?",
    ],
  },
  {
    id: "sierra-vista-unified",
    name: "Sierra Vista Unified",
    meetings: 3,
    faqs: [
      "What school safety and security updates were discussed at Sierra Vista Unified?",
      "Were there budget discussions at the last Sierra Vista board meeting?",
      "What curriculum or program changes were approved at Sierra Vista Unified?",
    ],
  },
  {
    id: "somerton-elementary",
    name: "Somerton Elementary",
    meetings: 3,
    faqs: [
      "What bilingual or ESL programs were discussed at Somerton Elementary?",
      "Were there any facility repairs approved at the last Somerton meeting?",
      "What budget updates were reported at Somerton Elementary?",
    ],
  },
  {
    id: "tempe-school",
    name: "Tempe Elementary",
    meetings: 3,
    faqs: [
      "What were the main topics at the last Tempe Elementary board meeting?",
      "Were there any budget discussions at Tempe Elementary?",
      "What school facility updates were discussed at Tempe Elementary?",
    ],
  },
  {
    id: "tempe-union-high",
    name: "Tempe Union High",
    meetings: 3,
    faqs: [
      "What career and technical education programs were discussed at Tempe Union High?",
      "Were there any budget or finance updates at the last Tempe Union meeting?",
      "What student achievement or graduation reports were presented?",
    ],
  },
  {
    id: "tolleson-union-high",
    name: "Tolleson Union High",
    meetings: 3,
    faqs: [
      "What new academic programs were discussed at Tolleson Union High?",
      "Were there budget approvals at the last Tolleson Union board meeting?",
      "What personnel or administrative changes were announced at Tolleson?",
    ],
  },
  {
    id: "toltec-elementary",
    name: "Toltec Elementary",
    meetings: 3,
    faqs: [
      "What school improvement plans were discussed at Toltec Elementary?",
      "Were there any facility expansion updates at the last Toltec meeting?",
      "What budget items were approved at Toltec Elementary?",
    ],
  },
  {
    id: "tucson-unified",
    name: "Tucson Unified",
    meetings: 3,
    faqs: [
      "What desegregation or equity updates were discussed at Tucson Unified?",
      "Were there budget discussions at the last Tucson Unified board meeting?",
      "What community or parent feedback was presented at Tucson Unified?",
    ],
  },
  {
    id: "vail-unified",
    name: "Vail Unified",
    meetings: 3,
    faqs: [
      "What new school construction was discussed at Vail Unified?",
      "Were there any technology or innovation program updates?",
      "What budget approvals were made at the last Vail Unified meeting?",
    ],
  },
  {
    id: "washington-elementary",
    name: "Washington Elementary",
    meetings: 3,
    faqs: [
      "What school improvement initiatives were discussed at Washington Elementary?",
      "Were there any facility safety updates at the last Washington meeting?",
      "What academic program changes were approved at Washington Elementary?",
    ],
  },
  {
    id: "wickenburg-unified",
    name: "Wickenburg Unified",
    meetings: 3,
    faqs: [
      "What rural school funding challenges were discussed at Wickenburg Unified?",
      "Were there any facility or transportation updates at the last meeting?",
      "What budget approvals were made at Wickenburg Unified?",
    ],
  },
  {
    id: "winslow-unified",
    name: "Winslow Unified",
    meetings: 3,
    faqs: [
      "What Native American education programs were discussed at Winslow Unified?",
      "Were there any grant or federal funding updates at the last meeting?",
      "What facility improvements were approved at Winslow Unified?",
    ],
  },
  {
    id: "yuma-elementary",
    name: "Yuma Elementary",
    meetings: 3,
    faqs: [
      "What bilingual education updates were discussed at Yuma Elementary?",
      "Were there facility or safety approvals at the last Yuma Elementary meeting?",
      "What budget discussions occurred at Yuma Elementary?",
    ],
  },
  {
    id: "yuma-union-high",
    name: "Yuma Union High",
    meetings: 3,
    faqs: [
      "What career and technical education programs were discussed at Yuma Union High?",
      "Were there any budget discussions at the last Yuma Union High meeting?",
      "What student achievement reports were presented at Yuma Union High?",
    ],
  },
];

export const UPDATED_DATES: Record<string, string> = {
  "agua-fria-union-high": "Oct 27, 2024",
  "ajo-unified": "Oct 29, 2024",
  "alhambra-elementary": "Oct 28, 2024",
  "apache-junction-unified": "Oct 28, 2024",
  "blue-ridge-unified": "Oct 25, 2024",
  "bullhead-city": "Oct 28, 2024",
  "cartwright-elementary": "Oct 30, 2024",
  "casa-grande-elementary": "Oct 29, 2024",
  "casa-grande-union-high": "Oct 28, 2024",
  "catalina-foothills-unified": "Oct 27, 2024",
  "cave-creek-unified": "Oct 28, 2024",
  "chandler-unified": "Oct 28, 2024",
  "chino-valley-unified": "Oct 28, 2024",
  "colorado-river-union-high": "Oct 29, 2024",
  "continental-elementary": "Oct 28, 2024",
  "cottonwood-oak-creek": "Oct 27, 2024",
  "creighton-elementary": "Oct 28, 2024",
  "deer-valley-unified": "Oct 28, 2024",
  "douglas-unified": "Oct 28, 2024",
  "dysart-unified": "Oct 28, 2024",
  "florence-unified": "Oct 28, 2024",
  "fountain-hills-unified": "Oct 28, 2024",
  "gadsden-elementary": "Oct 29, 2024",
  "gilbert-unified": "Oct 28, 2024",
  "glendale-elementary": "Oct 28, 2024",
  "higley-unified": "Oct 28, 2024",
  "humboldt-unified": "Oct 28, 2024",
  "indian-oasis-baboquivari": "Oct 29, 2024",
  "isaac-school": "Oct 29, 2024",
  "jo-combs-unified": "Oct 29, 2024",
  "joseph-city-unified": "Oct 28, 2024",
  "kingman-unified": "Oct 28, 2024",
  "kyrene-elementary": "Oct 29, 2024",
  "lake-havasu-unified": "Oct 28, 2024",
  "laveen-elementary": "Oct 29, 2024",
  "liberty-elementary": "Oct 29, 2024",
  "litchfield-elementary": "Oct 29, 2024",
  "littleton-elementary": "Oct 29, 2024",
  "madison-elementary": "Oct 29, 2024",
  "marana-unified": "Oct 29, 2024",
  "maricopa-unified": "Oct 28, 2024",
  "mesa-unified": "Oct 28, 2024",
  "osborn-elementary": "Oct 28, 2024",
  "page-unified": "Oct 29, 2024",
  "paradise-valley-unified": "Oct 28, 2024",
  "peoria-unified": "Oct 29, 2024",
  "phoenix-elementary": "Oct 29, 2024",
  "phoenix-union-high": "Oct 29, 2024",
  "pinon-unified": "Oct 28, 2024",
  "prescott-unified": "Oct 28, 2024",
  "queen-creek-unified": "Oct 28, 2024",
  "roosevelt-elementary": "Oct 29, 2024",
  "round-valley-unified": "Oct 28, 2024",
  "saddle-mountain-unified": "Oct 29, 2024",
  "sahuarita-unified": "Oct 29, 2024",
  "santa-cruz-valley-unified": "Oct 28, 2024",
  "santa-cruz-valley-union-high": "Oct 29, 2024",
  "scottsdale-unified": "Mar 18, 2025",
  "show-low-unified": "Oct 28, 2024",
  "sierra-vista-unified": "Oct 28, 2024",
  "somerton-elementary": "Oct 28, 2024",
  "tempe-school": "Oct 29, 2024",
  "tempe-union-high": "Oct 28, 2024",
  "tolleson-union-high": "Oct 28, 2024",
  "toltec-elementary": "Oct 29, 2024",
  "tucson-unified": "Oct 28, 2024",
  "vail-unified": "Oct 28, 2024",
  "washington-elementary": "Oct 28, 2024",
  "wickenburg-unified": "Oct 28, 2024",
  "winslow-unified": "Oct 28, 2024",
  "yuma-elementary": "Oct 28, 2024",
  "yuma-union-high": "Oct 28, 2024",
};
